version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
    depends_on:
      - db
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80